version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgresFormula
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=formuladata
    ports:
      - '5432:5432'
